CORE_OS_NAME = "Linux"

# The following are the revs of the v2.1.0-preview1 tags in each repository

CORE_SETUP_SRCREV = "5dfb58fad192286b0e801b606b2bb2f504d4e0e8"
CORECLR_SRCREV = "9d552fc39c8eb1a73af88fbb1cc45637dd669bf3"
COREFX_SRCREV = "be55ce3d44b7344c2a2272c514ee90fd9d5ffd48"

# Look at https://github.com/dotnet/core-setup/blob/master/dependencies.props

# CoreCLR version is from the "<MicrosoftNETCoreRuntimeCoreCLRPackageVersion>" entry
CORECLR_BUILD_MAJOR = "26024"
CORECLR_BUILD_MINOR = "02"

# CoreFX version is from the "<MicrosoftPrivateCoreFxNETCoreAppPackageVersion>" entry
COREFX_BUILD_MAJOR = "26024"
COREFX_BUILD_MINOR = "01"